Make sure circuits with constant ops can be serialized to JSON correctly
tilk/digitaljs pull request #67
Opened 2021-12-12 14:50 UTC by yuyichao

The fix is limited to OpConst to make sure we can handle the deserialization without any problems. Also fixed the implementation of ShiftConst to handle BigInt produced by constant folding.

Add tests to check the validity and stability of the JSON object.

Fix #65

.... took me longer to add the tests than to fix the issue....

2021-12-12 22:42 UTC, tilk requested changes
One more comment: if you look at `integrateArithConstant`, you'll see it only generates *Const cells for "small" constants - which was done for diagram readability reasons. But the constant is always of BigInt type, and it could already be a Number there.

2021-12-12 22:42 UTC, tilk commented on src/cells/arith.mjs
> +            if (constant <= BigInt(Number.MAX_SAFE_INTEGER))
What about negative numbers?

2021-12-12 22:42 UTC, tilk commented on src/cells/arith.mjs
> +            if (params.constant <= BigInt(Number.MAX_SAFE_INTEGER)) {
Negative numbers.

2021-12-12 22:42 UTC, tilk commented on tests/index.test.mjs
> +            testcon(randInt(0, Math.min(2**bits - 1, Number.MAX_SAFE_INTEGER)));
Negative numbers are not tested.

2021-12-19 13:41 UTC, yuyichao commented
Rebased and fixed.

This now eagerly convert the constant to `Number` when doing the transformation but it will still accept bigint if explicitly constructed.

2021-12-20 10:04 UTC, merged